import * as P from "../app/services/pricestock.mjs";
let fail = 0;
const chk = (l, g, w) => { const ok = String(g) === String(w); console.log((ok?"  ok  ":"  FAIL ")+`${l} (got=${g} want=${w})`); if(!ok) fail++; };
const o1 = { supplier_id:1, code:"A1", status:1, product_prices:[{region_id:10,base_price:100,promo_price:90,purchasing_price:70},{region_id:20,base_price:110}], products_stocks:[{warehouse_id:1,quantity:5},{warehouse_id:2,quantity:3}] };
const o2 = { supplier_id:2, code:"B2", status:1, product_prices:[{region_id:10,base_price:80}], products_stocks:[{warehouse_id:1,quantity:2}] };
chk("supplierId scalar", P.offerSupplierId(o1), 1);
chk("supplierId legacy", P.offerSupplierId({supplier:{id:7}}), 7);
chk("region prio 20→110", P.priceForOffer(o1,[20,10]).base, 110);
chk("region prio 10→100", P.priceForOffer(o1,[10]).base, 100);
chk("min → 80", P.resolvePrice([o1,o2],[10],[],"min").regular, 80);
chk("priority [1] → 100", P.resolvePrice([o1,o2],[10],[1],"priority").regular, 100);
chk("supplier-fixed 2 → 80", P.resolvePrice([o1,o2],[10],[],"supplier",2).regular, 80);
chk("promo 90<100 → sale 90", P.resolvePrice([o1],[10],[],"min",0,true).sale, 90);
chk("no promo region20 → sale null", String(P.resolvePrice([o1],[20],[],"min",0,true).sale), "null");
chk("stock sum = 10", P.resolveStock([o1,o2]), 10);
const a = P.signature({regular:100,sale:null,manage:false,qty:5,status:"instock"});
const b = P.signature({regular:100,sale:null,manage:false,qty:99,status:"instock"});
chk("sig ignores qty when manage off", a===b?"1":"0", "1");
const rec = P.resolveRecord([o1,o2], {region_prio:[10],strategy:"min",promo_as_sale:true,manage_stock:true,decimal_stock:false});
chk("record qty=10", rec.qty, 10);
chk("record status instock", rec.status, "instock");
console.log(fail===0 ? "\nALL PASS" : `\n${fail} FAILED`);
process.exit(fail?1:0);
